### ISSUE TITLE
asyncio incompatibility with Rasbian Buster and python:3.9 base image

### ISSUE THREAD

**Issue by astephon88** [BrewBlox/brewblox-plugin-boilerplate#46]
There appears to be a bug in the version of libseccomp2 that is used in Buster-based OS's that causes the following error when trying to use asyncio inside a container using the python:3.9 base image on a host running Rasbian Buster (and presumably all Buster-based OS's):
```
brewfather-uploader_1  | 2021-11-17T18:03:11.551122661Z   File "/usr/local/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
brewfather-uploader_1  | 2021-11-17T18:03:11.552624275Z     return get_event_loop_policy().new_event_loop()
brewfather-uploader_1  | 2021-11-17T18:03:11.552730004Z   File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
brewfather-uploader_1  | 2021-11-17T18:03:11.554136515Z     return self._loop_factory()
brewfather-uploader_1  | 2021-11-17T18:03:11.554301515Z   File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
brewfather-uploader_1  | 2021-11-17T18:03:11.554896150Z     super().__init__(selector)
brewfather-uploader_1  | 2021-11-17T18:03:11.555004379Z   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
brewfather-uploader_1  | 2021-11-17T18:03:11.555625265Z     super().__init__()
brewfather-uploader_1  | 2021-11-17T18:03:11.555746359Z   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
brewfather-uploader_1  | 2021-11-17T18:03:11.556805317Z     self._clock_resolution = time.get_clock_info('monotonic').resolution
brewfather-uploader_1  | 2021-11-17T18:03:11.556951150Z PermissionError: [Errno 1] Operation not permitted
```
The problem can be fixed by updating `libseccomp2` from the `buster-backports` repo. The issue is also not present if the container is using the `python:3.9-buster` base image. If you do not want require Rasbian >= 11 as a prereq, ask the users to enable the backports repo, or somehow put it in the install script to detect Buster-based OSs add update `libseccomp2` if necessary, it would probably be best to change the Dockerfile in this template to use `python.3.9-buster` and `python.3.9-buster-slim` so that anyone using it will have images compatible with buster out of the box.

**Comment by steersbob** [comment]
Related: https://github.com/moby/moby/issues/40734

There's no reason to suspect that Buster-based images won't run on Bullseye hosts, and Buster is in LTS support until 2024. 
Changing the Docker image base is preferable to running host-side compatibility checks.
